### PR TITLE
adds arangosearch mention to indexes page

### PR DESCRIPTION
**Pull request by cw00dw0rd**
- The ArangoSearch section isn't mentioned on the indexing page but I think it should be since it lives there now.

### CODE REVIEW

**Comment by Simran-B** [comment]
Yes, thanks!
I would word it differently, though. Views are more than inverted indexes, and I would like to avoid any confusion with the upcoming per-collection inverted indexes.

**Comment by cw00dw0rd** [comment]
I agree that there is a better way to phrase it. My goal was to inform the reader about why ArangoSearch is being included in the indexing section, since it is more than just an index. 
Have any suggestions?

Since the guides cover all of ArangoSearch we could just do something like
```
How to use ArangoSearch views, analyzers, and functions.
```

**Comment by ansoboleva** [comment]
Implemented @cw00dw0rd's suggestion.

**Review by ansoboleva — APPROVED** [review]
reviewed

**Pull request merged**
