### PR TITLE
DOC-141/auto-shard-rebalance

### PR DESCRIPTION
**Pull request by nerpaula**
Upstream: https://github.com/arangodb/arangodb/pull/16511

### CODE REVIEW

**Comment by Simran-B** [comment]
Still needs
- release notes (new features, API changes)
- maybe a reference in the Manual? A guide explaining imbalances and how to use this API in practice would be nice

**Comment by ansoboleva** [comment]
The release notes should be updated as part of this PR. The conceptual info will be added in a separate PR.

**Comment by ansoboleva** [comment]
https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/2234/

**Review by ansoboleva — APPROVED** [review]
reviewed

**Pull request merged**
