### PR TITLE
SmartJoin to SmartJoins

### PR DESCRIPTION
**Pull request by sonyarianto**
for consistency feature name

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @sonyarianto 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by sonyarianto** [comment]
@OmarAyo I think I already submit the CLA, can you check again? CC @Simran-B

**Comment by sonyarianto** [comment]
@OmarAyo I've sent it on March 26 via e-mail sony@bolabanget.com to cla@arangodb.com can you check it again.

**Comment by Simran-B** [comment]
Yes, we received the CLA a long time ago.

The optimizer rule is called `smart-joins`, so I think it's fine to consistently call it SmartJoins. Need to check additional files for naming.

**Pull request merged**
