### PR TITLE
Adding Aragog to list of community integrations

### PR DESCRIPTION
**Pull request by Nainterceptor**

### CODE REVIEW

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Comment by cw00dw0rd** [comment]
@cla-bot check

**Comment by Simran-B** [comment]
Thanks a lot for your contribution to ArangoDB!

We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by Nainterceptor** [comment]
Dear @Simran-B, I've signed it, the Saturday, May 21st, 2022 at 18:29 (Paris time)

**Comment by Simran-B** [comment]
Apologies, @Nainterceptor. A coworker confirmed that it arrived. Thank you very much!

**Pull request merged**
