### PR TITLE
fix: correct documentation for 'null' that suggests empty arrays & objects are falsy

### PR DESCRIPTION
**Pull request by obataku**
closes https://github.com/arangodb/docs/issues/626

Signed-off-by: obataku <19821199+obataku@users.noreply.github.com>

### CODE REVIEW

**Comment by Simran-B** [comment]
Thanks a lot for your contribution to ArangoDB!

We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by obataku** [comment]
> Thanks a lot for your contribution to ArangoDB!
> 
> We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf
> 
> You can scan and email the CLA PDF file to [cla@arangodb.com](mailto:cla@arangodb.com) or send it via fax to +49-221-2722999-88.

thanks for responding, @Simran-B, although I have a few questions: is this CLA made public? if not, what sorts of privacy guarantees do I have? I'm only slightly concerned about divulging so much personal information 🙂

**Comment by Simran-B** [comment]
Fixed in https://github.com/arangodb/docs/commit/abf37ea7daf8890236ca4559327b81f93b5a7275

**Comment by obataku** [comment]
while your PR seems to have obviated mine, @Simran-B, I'd still like to learn more about the usage & privacy guarantees surrounding these signed CLAs so I can familiarize myself ahead of future contributions. despite searching around I was unable to find anything more specific so any and all pointers are welcome

**Comment by obataku** [comment]
hi @Simran-B, have you had a chance to review my earlier comments above? I'm still eager to learn more so I know what to expect wrt future contributions 🙂

**Comment by Simran-B** [comment]
Hi @obataku, I passed this up to management but haven't gotten an official statement yet.

**Pull request closed without merging**
