### PR TITLE
Partially revert #1175 because `primarySortCache` will be released in v3.9.6

### PR DESCRIPTION
**Pull request by Dronplane**
~~Upstream: https://github.com/arangodb/arangodb/pull/17602 (adds missing `cache` option to storedValues)~~

Too late to include upstream PRs for v3.9.5, added the changes to #1191 for v3.9.6 instead.

### CODE REVIEW

**Comment by Simran-B** [comment]
Is this supposed to revert the changes of #1175 and #1183 related to `primarySortCache`, and only this option?

It's incomplete: https://github.com/arangodb/docs/blob/bug-fix/temporary-remove-not-supported-fields/3.9/arangosearch-performance.md?plain=1#L123-L156

**Comment by Dronplane** [comment]
>Is this supposed to revert the changes of https://github.com/arangodb/docs/pull/1175 related to primarySortCache, and only this option?

Yes. Till 3.9.6. At this version this option should be returned  and one more added.

**Comment by Simran-B** [comment]
Is the `cache` option of `storedValues` immutable like the rest of `storedValues`?

**Comment by Dronplane** [comment]
>Is the cache option of storedValues immutable like the rest of storedValues?

yes

**Pull request merged**
