### PR TITLE
Add commas

### PR DESCRIPTION
**Pull request by lodestone**
- Add commas to introductory clauses.
- Add oxford comma. [^1]

[^1]: [Strippers, JFK, Stalin, and the Oxford Comma](https://www.verbicidemagazine.com/2011/09/20/strippers-jfk-and-stalin-illustrate-why-you-should-use-the-serial-comma/)

### CODE REVIEW

**Comment by lodestone** [comment]
Strange. 🤔 

There should be a CLA from me on file already. Perhaps it wasn't added to the cla-bot. On Saturday February 17th 2018 at 11:57 PM (CST), I sent my signed copy to cla@arangodb.com. As you can see from the screenshot below, I received a reply several days later on February 28th from Santo Leto.

@cw00dw0rd - Please let me know how I should proceed on this.

Cheers.

----



## Email Details

```email
Date: Sat, 17 Feb 2018 23:57:38 -0600
From: Matthew Petty <matt@kizmeta.com>
To: cla@arangodb.com
Message-ID: <600d42d8-4d42-4eb7-b9ba-7955fbb1a5a9@Spark>
Subject: CLA Matt Petty

Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="CLA-signed.pdf"
```


## **Gmail Screenshot**

I received this reply to my initial email, to which I replied with my Github username.

Screen Shot 2022-01-12 at 4 43 31 AM

**Comment by cw00dw0rd** [comment]
@cla-bot check

**Comment by cw00dw0rd** [comment]
@lodestone thanks again for these updates, would you mind adding these fixes to the other versions as well (3.6, 3.7, etc..)?

**Comment by lodestone** [comment]
> ... would you mind adding these fixes to the other versions as well (3.6, 3.7, etc..)?

I've updated files also named `foxx-guides-browser.md` in other `docs/3.x` directories.

@cw00dw0rd let me know if any additional work is needed!

Cheers

**Comment by cw00dw0rd** [comment]
Thanks again @lodestone for the fixes!

**Pull request merged**
