### PR TITLE
fix login example

### PR DESCRIPTION
**Pull request by WhileOneK**
In the example above the authentication result is stored in the password field.

### CODE REVIEW

**Comment by Simran-B** [comment]
Thanks a lot for your contribution to ArangoDB!

We would like to accept your patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by WhileOneK** [comment]
Thank you. I have send the cla pdf to the email like requested.

**Comment by joerg84** [comment]
CLA received, thanks for the contribution!

@Simran-B please proceed

**Review by Simran-B — APPROVED** [review]
The example was apparently inspired by the dependencies guide, which names the attribute `authData` that stores the hashed password.

Thanks for fixing this!

**Pull request merged**
