### PR TITLE
- added tash

### PR DESCRIPTION
**Pull request by neel**
added community C++ developed library tash (https://gitlab.com/neel.basu/tash)

### CODE REVIEW

**Comment by Simran-B** [comment]
Thanks a lot for your contribution to ArangoDB @neel!

I wonder whether this counts as driver or integration. I would count a query build as integration, but it looks like you also implemented some functionality to communicate with the server?

Furthermore, for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). We use an Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

**Comment by neel** [comment]
Yes it communicates with the server through the HTTP API. However the project that I was working on then required complicated AQL. So simple creation, updation etc.. was not enough. So an AQL builder DSL was also written to generate the AQL and send that to the server and fetch the result set.
I'll send the CLA.

**Comment by neel** [comment]
@Simran-B sent signed CLA as mail.

**Comment by Simran-B** [comment]
Thanks again. As soon as the docs are published again, tash will beon the list.

**Pull request merged**
