### PR TITLE
Change default output format of arangoexport from `json` to `jsonl`

### PR DESCRIPTION
**Pull request by jsteemann**

### CODE REVIEW

**Comment by ansoboleva** [comment]
@Simran-B please follow up on this PR according to https://arangodb.atlassian.net/browse/DOC-218

**Review by Simran-B — APPROVED** [review]

**Review by ansoboleva — CHANGES_REQUESTED** [review]
@Simran-B Please also update this page:

programs-arangoexport.md - it should also mention JSONL as it's the default output format now.

**Comment by Simran-B** [comment]
@ansoboleva Do you refer to "like JSON, CSV or XML"? It's a non-exhaustive list. Should XGMML also be mentioned?

**Comment by ansoboleva** [comment]
@Simran-B yes, this bit. The list doesn't have to be exhaustive, but it should mention the default format.

**Comment by Simran-B** [comment]
JSONL is less known than JSON, so we should mention both, but the only format not mentioned would then be XGMML. BTW. the proper name is JSON Lines, not JSONL. Which one should we use?

**Review by ansoboleva — APPROVED** [review]

**Pull request merged**
