### PR TITLE
correct collection name

### PR DESCRIPTION
**Pull request by diyarfaraj**
I believe it should be "users" at the end of the query.

### CODE REVIEW

**Comment by Simran-B** [comment]
The example is correct, it shows that you can read from a collection using a FOR loop and write to a different collection. Is the example description not clear enough perhaps?

> An update operation may update arbitrary documents which do not need to be identical
to the ones produced by a preceding `FOR` statement

**Comment by diyarfaraj** [comment]
> The example is correct, it shows that you can read from a collection using a FOR loop and write to a different collection. Is the example description not clear enough perhaps?
> 
> > An update operation may update arbitrary documents which do not need to be identical
> > to the ones produced by a preceding `FOR` statement

For me with a few months experience with Arango, that specific explanation was not clear, to be honest. But maybe it's just me :)

**Comment by Simran-B** [comment]
Let me know if this is clear enough: https://github.com/arangodb/docs/pull/1074

**Comment by diyarfaraj** [comment]
very nice, much better thanks!

**Pull request closed without merging**
